# Host preview build for the HappyPot LVGL UI.
#
# Renders each UI screen to sim/out/<name>.png and <name>.bmp without Zephyr or
# flashing. Run:
#   powershell -ExecutionPolicy Bypass -File build.ps1        (from cmd)
#   ./build.ps1                                               (from PowerShell)
# Requires a host GCC. Cross-platform (Windows/Linux/macOS) under PowerShell 7.
#   Windows: defaults to MSYS2 MinGW + NCS LVGL.
#   Linux/macOS: defaults to gcc/g++ from PATH; pass -Lvgl <path-to-lvgl>.
# LVGL is cached after the first build; -Clean forces a full rebuild.
param(
    [string]$Gcc,
    [string]$Gpp,
    [string]$Lvgl,
    [switch]$Clean   # force a full LVGL rebuild (otherwise LVGL is cached)
)
$ErrorActionPreference = "Stop"

# OS-aware defaults. $IsWindows is $null on Windows PowerShell 5.1 -> treat as Windows.
$onWindows = ($IsWindows -ne $false)
if (-not $Gcc) { $Gcc = if ($onWindows) { "C:\msys64\mingw64\bin\gcc.exe" } else { "gcc" } }
if (-not $Gpp) { $Gpp = if ($onWindows) { "C:\msys64\mingw64\bin\g++.exe" } else { "g++" } }
if (-not $Lvgl) {
    $Lvgl = if ($onWindows) { "C:\ncs\v3.4.0\modules\lib\gui\lvgl" }
    else { "$HOME/ncs/v3.4.0/modules/lib/gui/lvgl" }
}

$sim = $PSScriptRoot
$root = Split-Path $sim -Parent
$src = Join-Path $root "src"
$out = Join-Path $sim "out"
$obj = Join-Path $sim "build"
New-Item -ItemType Directory -Force -Path $out, $obj | Out-Null

$inc = @("-I$Lvgl", "-I$sim", "-I$src")

# The version comes from the one place it exists, <repo>/VERSION -- the same file Zephyr reads to
# build APP_VERSION_STRING for the firmware. Here there is no Zephyr and so no generated header, so
# parse it and hand it to the compiler. src/version.hpp errors out if this is missing rather than
# quietly inventing a number, because a preview that shows a version the device does not have is
# worse than one that will not build.
$verFile = Get-Content (Join-Path $root "VERSION") -Raw
$maj = [regex]::Match($verFile, 'VERSION_MAJOR\s*=\s*(\d+)').Groups[1].Value
$min = [regex]::Match($verFile, 'VERSION_MINOR\s*=\s*(\d+)').Groups[1].Value
$pat = [regex]::Match($verFile, 'PATCHLEVEL\s*=\s*(\d+)').Groups[1].Value
if (-not ($maj -and $min -and $pat)) { throw "Could not read a version out of $root\VERSION" }
$version = "$maj.$min.$pat"
Write-Host "==> Version $version (from VERSION)" -ForegroundColor DarkGray

# HAPPYPOT_VERSION has to reach the compiler as a string LITERAL -- src/version.hpp and the boot
# label paste it. Handing that to gcc as a -D means getting quotes through PowerShell's
# native-argument mangling: one escape too many and the macro becomes "\"0.2.0\"", which compiles
# perfectly and only shows up in the rendered image. So: no quoting contest. Write the define into
# a header and force-include it.
$verHeader = Join-Path $obj "happypot_version_sim.h"
Set-Content -Path $verHeader -Encoding ASCII -Value @(
    "/* Generated by sim/build.ps1 from <repo>/VERSION. Do not edit. */",
    "#pragma once",
    "#define HAPPYPOT_VERSION `"$version`""
)
$def = @("-DLV_CONF_INCLUDE_SIMPLE", "-DLV_LVGL_H_INCLUDE_SIMPLE", "-include", $verHeader)
$warn = @("-w")   # LVGL is noisy; we only care about our own code compiling

Write-Host "==> Compiling C++ (UI + sim harness)" -ForegroundColor Cyan
$cppSrc = @(
    (Join-Path $src "ui/display_ui.cpp"),
    (Join-Path $sim "ui_platform_sim.cpp"),
    (Join-Path $sim "sim.cpp")
)
$cppObj = @()
foreach ($f in $cppSrc) {
    $o = Join-Path $obj ((Split-Path $f -Leaf) + ".o")
    & $Gpp -std=c++17 -O1 @warn @def @inc -c $f -o $o
    if ($LASTEXITCODE -ne 0) { throw "compile failed: $f" }
    $cppObj += $o
}

# LVGL almost never changes, so compile it once into a single cached relocatable
# object (build/lvgl.o) and reuse it. Rebuild only on -Clean, if the cache is
# missing, or if lv_conf.h was touched (that re-shapes the whole LVGL build).
$lvglObj = Join-Path $obj "lvgl.o"
$conf = Join-Path $sim "lv_conf.h"
$rebuild = $Clean -or -not (Test-Path $lvglObj) -or
((Get-Item $conf).LastWriteTime -gt (Get-Item $lvglObj).LastWriteTime)

if ($rebuild) {
    Write-Host "==> Compiling LVGL (cached afterwards)" -ForegroundColor Cyan
    # Exclude only backend drivers (SDL/X11/etc. pull external headers). Everything
    # else under src/ is guarded by LV_USE_* and compiles to ~nothing when disabled.
    # Regex is separator-agnostic so it also excludes on Linux (forward slashes).
    $lvglSrc = Get-ChildItem -Recurse -Path (Join-Path $Lvgl "src") -Filter *.c |
    Where-Object { $_.FullName -notmatch '[\\/]drivers[\\/]' } |
    ForEach-Object { $_.FullName }
    Write-Host "    $($lvglSrc.Count) LVGL .c files"

    # gcc @responsefile to dodge the Windows command-line length limit.
    # NB: gcc unescapes backslashes inside @files, so emit forward slashes.
    $rsp = Join-Path $obj "lvgl_sources.rsp"
    ($lvglSrc | ForEach-Object { '"' + ($_ -replace '\\', '/') + '"' }) |
    Set-Content -Path $rsp -Encoding ASCII

    # -r links all the compiled units into one relocatable object we can cache.
    & $Gcc -r -O1 @warn @def @inc "@$rsp" -o $lvglObj
    if ($LASTEXITCODE -ne 0) { throw "LVGL compile failed" }
}
else {
    Write-Host "==> Using cached LVGL (build.ps1 -Clean to rebuild)" -ForegroundColor DarkGray
}

# The generated 1-bit artwork (src/ui_images/) and fonts (src/fonts/) -- single source of
# truth, shared with the firmware -> cached images.o, rebuilt when any of them changes.
$imgObj = Join-Path $obj "images.o"
$imgSrc = @(Get-ChildItem -Path (Join-Path $src "ui_images") -Filter *.c -ErrorAction SilentlyContinue) +
@(Get-ChildItem -Path (Join-Path $src "fonts") -Filter *.c -ErrorAction SilentlyContinue)
if ($imgSrc.Count -gt 0) {
    $newest = ($imgSrc | Measure-Object -Property LastWriteTime -Maximum).Maximum
    if ($Clean -or -not (Test-Path $imgObj) -or $newest -gt (Get-Item $imgObj).LastWriteTime) {
        Write-Host "==> Compiling $($imgSrc.Count) UI images (cached)" -ForegroundColor Cyan
        $irsp = Join-Path $obj "images.rsp"
        ($imgSrc | ForEach-Object { '"' + ($_.FullName -replace '\\', '/') + '"' }) |
        Set-Content -Path $irsp -Encoding ASCII
        & $Gcc -r -O1 @warn @def @inc "@$irsp" -o $imgObj
        if ($LASTEXITCODE -ne 0) { throw "image compile failed" }
    }
}

Write-Host "==> Linking happypot_sim.exe" -ForegroundColor Cyan
$exe = Join-Path $obj "happypot_sim.exe"
$linkObjs = @($lvglObj)
if (Test-Path $imgObj) { $linkObjs += $imgObj }
$linkObjs += $cppObj
& $Gcc -O1 @linkObjs -lstdc++ -lm -o $exe
if ($LASTEXITCODE -ne 0) { throw "link failed" }

# Once per application (see apps/). The two do not draw the same device -- the Matter build names
# itself on the splash, has a Network menu row and a pairing screen behind it -- and a screen only
# one build has is exactly the screen a mockup is needed for.
foreach ($variant in @("bthome", "matter")) {
    $dir = Join-Path $out $variant
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
    Write-Host "==> Rendering screens: $variant" -ForegroundColor Cyan
    Push-Location $dir
    try { & $exe $variant } finally { Pop-Location }
    if ($LASTEXITCODE -ne 0) { throw "sim run failed for $variant" }
}

Write-Host "==> Done. Images in $out" -ForegroundColor Green
Get-ChildItem $out -Include *.png -Recurse | ForEach-Object {
    "{0,-12} {1}" -f $_.Directory.Name, $_.Name
}
