// AUTO-GENERATED by tools/svg_to_lvgl.py - do not edit.
#pragma once

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

LV_IMAGE_DECLARE(boot);
LV_IMAGE_DECLARE(cal_done);
LV_IMAGE_DECLARE(cal_dry);
LV_IMAGE_DECLARE(cal_reset);
LV_IMAGE_DECLARE(cal_wet);
LV_IMAGE_DECLARE(lowbat);
LV_IMAGE_DECLARE(s0_happy);
LV_IMAGE_DECLARE(s0_meh);
LV_IMAGE_DECLARE(s0_thirsty);
LV_IMAGE_DECLARE(s1_happy);
LV_IMAGE_DECLARE(s1_meh);
LV_IMAGE_DECLARE(s1_thirsty);

#ifdef __cplusplus
}
#endif
