#!/usr/bin/env python3
"""Rasterize SVGs to 1-bit PNG and emit LVGL C image arrays.

Pipeline:  SVG --svglib--> PIL RGBA --composite-on-white--> L --dither--> 1
           --> PNG --LVGLImage.py--> .c (LV_COLOR_FORMAT_I1)

Each SVG in --src becomes a .c file in --out whose LVGL symbol matches the
filename stem. Pick stems that are valid C identifiers (no leading digit).

Usage:
    python tools/svg_to_lvgl.py
    python tools/svg_to_lvgl.py --src img --out src/ui_images --size 200
"""

from __future__ import annotations

import argparse
import glob
import os
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image
from reportlab.graphics import renderPM
from svglib.svglib import svg2rlg

REPO_ROOT = Path(__file__).resolve().parent.parent


def find_lvgl_script() -> Path | None:
    """Best-effort discovery of LVGLImage.py inside an NCS/Zephyr install."""
    candidates: list[Path] = []
    zephyr_base = os.environ.get("ZEPHYR_BASE")
    if zephyr_base:
        candidates.append(Path(zephyr_base).parent / "modules/lib/gui/lvgl/scripts/LVGLImage.py")
    for ncs in sorted(glob.glob("C:/ncs/v*"), reverse=True):
        candidates.append(Path(ncs) / "modules/lib/gui/lvgl/scripts/LVGLImage.py")
    for c in candidates:
        if c.is_file():
            return c
    return None


def rasterize(svg_path: Path, size: int) -> Image.Image:
    """Render SVG to a `size x size` 1-bit PIL image, dithered, on white."""
    drawing = svg2rlg(str(svg_path))
    if drawing is None:
        raise RuntimeError(f"svglib failed to parse {svg_path}")

    src_w = float(drawing.width) or 1.0
    src_h = float(drawing.height) or 1.0
    scale = size / max(src_w, src_h)
    drawing.width = src_w * scale
    drawing.height = src_h * scale
    drawing.scale(scale, scale)

    rgba = renderPM.drawToPIL(drawing, bg=0xFFFFFF).convert("RGBA")

    # Center on a `size x size` white canvas (handles non-square SVGs).
    canvas = Image.new("RGB", (size, size), "white")
    off = ((size - rgba.width) // 2, (size - rgba.height) // 2)
    canvas.paste(rgba, off, mask=rgba.split()[-1])

    gray = canvas.convert("L")
    return gray.convert("1", dither=Image.FLOYDSTEINBERG)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", default="img", help="SVG source folder (default: img)")
    ap.add_argument("--out", default="src/ui_images", help="Output folder for .c files (default: src/ui_images)")
    ap.add_argument("--size", type=int, default=200, help="Target square size in px (default: 200)")
    ap.add_argument("--lvgl-script", default=None, help="Path to LVGLImage.py (auto-discovered if omitted)")
    ap.add_argument("--keep-png", action="store_true", help="Also copy the 1-bit PNGs into --out for inspection")
    args = ap.parse_args()

    src_dir = (REPO_ROOT / args.src).resolve()
    out_dir = (REPO_ROOT / args.out).resolve()
    if not src_dir.is_dir():
        print(f"error: source folder not found: {src_dir}", file=sys.stderr)
        return 2

    lvgl_script = Path(args.lvgl_script) if args.lvgl_script else find_lvgl_script()
    if lvgl_script is None or not lvgl_script.is_file():
        print("error: could not locate LVGLImage.py; pass --lvgl-script PATH", file=sys.stderr)
        return 2

    svgs = sorted(src_dir.glob("*.svg"))
    if not svgs:
        print(f"error: no .svg files in {src_dir}", file=sys.stderr)
        return 2

    out_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        for svg in svgs:
            png = tmp / (svg.stem + ".png")
            print(f"  rasterize {svg.name} -> {png.name} ({args.size}x{args.size}, 1-bit)")
            img = rasterize(svg, args.size)
            img.save(png)
            if args.keep_png:
                img.save(out_dir / png.name)

        print(f"  LVGLImage.py --cf=I1 --ofmt=C  ->  {out_dir}")
        cmd = [
            sys.executable, str(lvgl_script),
            "--ofmt=C", "--cf=I1",
            "-o", str(out_dir),
            str(tmp),
        ]
        result = subprocess.run(cmd, check=False)
        if result.returncode != 0:
            print("error: LVGLImage.py failed", file=sys.stderr)
            return result.returncode

    # Emit a single header that extern-declares every generated image, so
    # consumers can `#include "ui_images/ui_images.h"` instead of sprinkling
    # LV_IMAGE_DECLARE(...) themselves.
    header = out_dir / "ui_images.h"
    names = [svg.stem for svg in svgs]
    with header.open("w", newline="\n") as f:
        f.write("// AUTO-GENERATED by tools/svg_to_lvgl.py - do not edit.\n")
        f.write("#pragma once\n\n")
        f.write("#include <lvgl.h>\n\n")
        f.write("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")
        for n in names:
            f.write(f"LV_IMAGE_DECLARE({n});\n")
        f.write("\n#ifdef __cplusplus\n}\n#endif\n")

    print()
    print("Generated:")
    for c in sorted(out_dir.glob("*.c")):
        print(f"  {c.relative_to(REPO_ROOT)}")
    print(f"  {header.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
